title: "Davide Fucci"
baseurl: ""

first-name: 'Davide'
last-name: 'Fucci'
profpic: '/resources/img/profilepic.png'
profpic-retina: '/resources/img/profilepic@2x.png'
twitter: dfucci_
email: 'davide.fucci@bth.se'
github: 'dfucci'
location: 'Blekinge Institute of Technology'
location-url: ""


sass:
  style: compressed

livereload: true
