title: "Davide Fucci"
baseurl: ""

first-name: 'Davide'
last-name: 'Fucci'
twitter: dfucci_
email: 'davide.fucci@bth.se'
github: 'dfucci'
location: 'Blekinge Institute of Technology'
location-url: ""


sass:
  style: compressed

livereload: true
